/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (colin-mcrae-rally-2-0-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8003467Cu
#define func_8003467C BootEntry  /* alias */
